<?php
/**
 * @author    Sutunam
 * @copyright Copyright (c) 2024 Sutunam (http://www.sutunam.com/)
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductListItem;
use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Sutunam\LinkedProduct\Model\Config as ConfigData;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ConfigData $configData */
$configData = $this->helper(ConfigData::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);

if (!$configData->isEnable() || !$configData->isShowOnProductListing()) {
    return;
}

$showAvailableProductsCount = $configData->isShowAvailableProductsCount();
$showStockStatusText = $configData->isStockStatusTextProductListing();
$productsCountText = $configData->getAvailableProductsCountText();

/** @var Product $product */
$product = $block->getProduct();

if (!$product) {
    return;
}

$attributeToLink = $product->getData('attribute_to_link');

if (!$product->hasData('linked_products') &&
    !$product->hasData('available_products_count')) {
    return;
}

/** @var Template $itemRendererBlock */
$itemRendererBlock = $block->getLayout()->createBlock(AbstractProduct::class);
$itemRendererBlock->setTemplate('Sutunam_HyvaLinkedProduct::product/linked/item.phtml');
$itemRendererBlock->setData('show_stock_status_text', $showStockStatusText);
?>

<?php if ($showAvailableProductsCount):
    $count = (int) $product->getData('available_products_count') ?>
    <?php if (isset($productsCountText[$attributeToLink])): ?>
    <div class="flex w-full pt-3">
        <?php if ($count > 1): ?>
            <?= $escaper->escapeHtml(__($productsCountText[$attributeToLink]['plural'], $count)) ?>
        <?php endif; ?>
        <?php if ($count === 1): ?>
            <?= $escaper->escapeHtml(__($productsCountText[$attributeToLink]['singular'])) ?>
        <?php endif; ?>
    </div>
    <?php endif; ?>
<?php else: ?>
    <div class="grid grid-cols-4 md:grid-cols-3 lg:grid-cols-4 gap-2 w-full pt-3">
        <?php foreach ($product->getData('linked_products') as $linkedProduct): ?>
            <?= $productListItemViewModel->getItemHtmlWithRenderer(
                $itemRendererBlock,
                $linkedProduct,
                $block,
                'grid',
                'short',
                'product_listing_linked_product',
                false
            ) ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
